### ISSUE TITLE
Support for multiple APIs

### ISSUE THREAD

**Issue by TO-koswald** [johannschopplich/nuxt-api-party#1]
Would be nice to have support for multiple apis - with multiple composables generated: `useApi1Data`, `useApi2Data`

**Comment by johannschopplich** [comment]
Agreed! It's on the roadmap.

**Comment by johannschopplich** [comment]
✅ Released in [v0.3.0](https://github.com/johannschopplich/nuxt-api-party/releases/tag/v0.3.0).
