### ISSUE TITLE
Use Runtime Config Instead of `process.env` vars 

### ISSUE THREAD

**Issue by Robinrrr** [johannschopplich/nuxt-api-party#13]
I have the problem that I can't set the environment variables during build, but only during runtime. Is it possible to use the nuxt runtimeconfig for the configuration of the URLs instead of the normal .env variables? 

For reference: 
like the nuxt proxy modul:
https://github.com/wobsoriano/nuxt-proxy#runtime-config

**Comment by johannschopplich** [comment]
Yes, you can. But I think those are two separate issues. If you can't set environment variables, why bother using the runtime config, when you can use the `apiParty` module options with hard-coded values? 

You choose between (given the possibility to hard-code URL, token etc.):

```ts
// `nuxt.config.ts`
export default defineNuxtConfig({
  modules: ['nuxt-api-party'],

  apiParty: {
    endpoints: {
      'json-placeholder': {
        url: process.env.JSON_PLACEHOLDER_API_BASE_URL,
        token: process.env.JSON_PLACEHOLDER_API_TOKEN
      }
    }
  }
})
```

and:

```ts
// `nuxt.config.ts`
export default defineNuxtConfig({
  modules: ['nuxt-api-party'],

  runtimeConfig: {
    apiParty: {
      endpoints: {
        'json-placeholder': {
          url: process.env.JSON_PLACEHOLDER_API_BASE_URL,
          token: process.env.JSON_PLACEHOLDER_API_TOKEN
        }
      }
    }
  }
})
```

**Comment by Robinrrr** [comment]
I have already tried it like in your example, but i get the error `No name provided for the API. Please set the name option. ` if I set it in the runtimeConfig instead the normal apiParty options

**Comment by johannschopplich** [comment]
Good point! The module lacked proper support for this feature. Should be fixed in https://github.com/johannschopplich/nuxt-api-party/commit/f7420e3aa028fe21ef63b8b10b5b18b6508139ae.

Please try again with v0.9.4 and give me a hint if that works now. Thanks!

**Comment by Robinrrr** [comment]
Many thanks for your effort! I try it later. I have misunderstood the use of runtimeConfig a bit. To change the values in rumtime i have to adjust the env variables like the structure of the runtimeConfig.

Example:

**nuxt.config.js**
```
runtimeConfig: {
	apiParty: {
		endpoints: {
			cms: {
				url: process.env.NUXT_API_PARTY_ENDPOINTS_CMS_URL,
			},
		},
	},
},
```

**.env**
```
# env variable need to look like this to change it in runtime
NUXT_API_PARTY_ENDPOINTS_CMS_URL=http://localhost:1337
```

**Comment by hs-tunji-oyeniran** [comment]
This worked https://github.com/johannschopplich/nuxt-api-party/issues/13#issuecomment-1451756829
