### ISSUE TITLE
Query change in route not detected properly

### ISSUE THREAD

**Issue by modbender** [johannschopplich/nuxt-api-party#14]
I was trying to implement pagination with hook `usePartyData`

On the page I have this code:
```js
const route = useRoute();
const { $apiUrl } = useNuxtApp();

const {
  data,
  error,
  pending,
} = await usePartyData($apiUrl("chapter"), {
  query: computed(() => ({
    page: route.query?.page || 1,
  })),
});
```

For pagination links I'm having separate custom pagination component which automatically generates pagination links from 1 to total pages using `NuxtLink` like below:
```html
<NuxtLink
  class="btn"
  :class="{ 'btn-active': item.selected }"
  :to="{ query: { ...$route.query, page: item.page } }"
>
          {{ item.page }}
</NuxtLink>
```

The pagination works perfectly fine and changes query `page` value in URL when I click on the link without any problem, the problem is after initial load, with data for page 1, I then click to page 2 which loads in the new data. But when I click back on page 1 the data rendered is still for page 2.

I have tested adding `route` returned from `useRoute()` to `watch` and tried with reactive variable and watching the variable and on change of route query value, I made it to change variable value and added this reactive variable to watch instead, but didn't work. I added both `route` and a reactive variable holding page number to `watch` and still didn't work.

I switched back to `useFetch` and tested, without any of these extra code, just with the initial code it works fine.

**Comment by johannschopplich** [comment]
You will probably have to disable the cache:

```ts
const {
  data,
  error,
  pending,
} = await usePartyData($apiUrl("chapter"), {
  query: computed(() => ({
    page: route.query?.page || 1,
  })),
cache: false,
});
```

See the documentation: https://github.com/johannschopplich/nuxt-api-party#usepartydata-respectively-pascal-cased-api-name

> Responses are cached between function calls for the same path based on a calculated hash. You can disable this behavior by setting `cache` to `false`.

**Comment by modbender** [comment]
That indeed works, but shouldn't something as important as query in URL changing re render with new data by default?

**Comment by johannschopplich** [comment]
You are right. The query is reactive and subsequently should change the cache key. Thus, it should not be necessary to use `cache: false`. I will investigate this!

**Comment by modbender** [comment]
Thank you, that's all from my side. You can close this issue whenever you want.

**Comment by johannschopplich** [comment]
Well, it actually works with `ref`. See the playground example: 

https://github.com/johannschopplich/nuxt-api-party/blob/b6da16e9a8718aaf3327feb694cca10d5735761e/playground/pages/index.vue#L12

Don't know why it doesn't work with the route query parameter.

**Comment by modbender** [comment]
I think it might have something to do with cache key.

**Comment by johannschopplich** [comment]
@modbender No, the cache key takes the query into account. I have updated the playground to use the route query instead of a ref: https://github.com/johannschopplich/nuxt-api-party/commit/9e27427a71c0fabc85e37737d2a3defcdcb2ce4f

It does work, as far as I can tell. Do you spot a difference between your use-case?

**Comment by johannschopplich** [comment]
The custom key is not supported by the generated composables. It is calculated with taking the endpoint ID into consideration as well as other parameters like the query.

Closing this as not reproducible.

**Comment by johannschopplich** [comment]
@sneakylenny Please open a new issue. Thanks!
