### ISSUE TITLE
Add a retry option to UseApiDataOptions 

### ISSUE THREAD

**Issue by klemenstraeger** [johannschopplich/nuxt-api-party#29]
### Describe the feature

Im currently using something like this in my project to retry a failed fetch.

```javascript
const fetchData = async () => {
    let tries = 0
    const maxTries = 3

    const { refresh, error, data } = await useApiData(
        "path/to/api",
    );
    while (error.value && tries < maxTries) {
        tries++;
        await refresh();
    }
    if (error.value) {
        //handle error..
    }
    return data.value
}
```

My suggstion would be to add an option to  `UseApiDataOptions`  to enable retries if a fetch fails. 

```javascript
await useApiData(
    "path/to/api",
    {
        retries: 3
    }
)
```
Thanks ! 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by johannschopplich** [comment]
Good idea. PR welcome. 🙋‍♂️

**Comment by johannschopplich** [comment]
@klemenstraeger @m0zz094 @linshujuan This feature has been implemented: https://nuxt-api-party.byjohann.dev/guide/retries.html
