### ISSUE TITLE
'apiParty' isn't being recognised in nuxt.config.ts

### ISSUE THREAD

**Issue by Luuk** [johannschopplich/nuxt-api-party#3]
Hi,

After installing api party and adding it to the modules, it seems that 'apiParty' isn't being recognised in nuxt.config.ts. It gives the following message: "Object literal may only specify known properties, and 'apiParty' does not exist in type 'NuxtConfig'."

![image](https://user-images.githubusercontent.com/34124413/205292737-d58af8ca-2df8-4443-aabf-238aaed546b5.png)

**Comment by johannschopplich** [comment]
Did you run `npm run dev` after installing? Nuxt has to generate the types for each module after each module installation. Also, try to reload your extensions.

**Comment by Luuk** [comment]
Thank you for the quick response, running the app and reloading my extensions after has fixed the issue!
