### ISSUE TITLE
Payload is not being updated after `refresh()`

### ISSUE THREAD

**Issue by 9M6** [johannschopplich/nuxt-api-party#31]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      experimental, vite, nitro, devtools, debug, ssr, css, imports, runtimeConfig, modules, apiParty
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/i18n@8.0.0-beta.13, @vueuse/nuxt@10.2.1, nuxt-typed-router@3.2.5, nuxt-lodash@2.5.0, nuxt-api-party@0.13.0, nuxt-icon@0.4.2
- Build Modules:    -
------------------------------

### Reproduction

1. Make a normal call to any Nuxi Api Party autogenerated functions with `cache: false`
2. Call `refresh()`
3. `watchEffect` the `data` payload and assign it to any `pinia` state

### Describe the bug

The `data` property should return the newly updated payload, but returns the old initial payload from the request.
The request is successful and I can see the data being sent over by the backend/proxy, but the data is not propagated to the `data` property.

The `watchEffect` methods throws successfully when `refresh` executes, but the data returned is the old data/payload (as there's missing fields and information from the payload`

**Comment by johannschopplich** [comment]
Please provide a minimum reproduction. Thanks!

**Comment by 9M6** [comment]
@johannschopplich I would like to apologies, after investigating on both the nuxt-api-party and my implementation I found that another function was updating the payload in the pinia store and thus making the specific payload unreactive, and the changes would not propagate on the pinia store. Again apologies and thank you for the support.
