### ISSUE TITLE
Generate types from Swagger/OpenAPI schemas

### ISSUE THREAD

**Issue by killjoy1221** [johannschopplich/nuxt-api-party#32]
### Describe the feature

A huge benefit of writing your backend endpoints using nuxt is the type inference in `useFetch` and `$fetch`. Not only do you get types for the path, but also the request and response data. You don't get that benefit when using API Party. Without types, it's not much of a party.

Some services provide a [json file](https://swagger.io/resources/open-api/) describing the API, including paths and component models. Some frameworks even provide the functionality by default.

## Configuration

I suggest implementing a config that can load a spec from a url, file, or object.

Here's an example.
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  modules: ['nuxt-api-party'],
  apiParty: {
    endpoints: {
      httpbin: {
        url: "https://httpbin.org",
        // URL to the API spec. Could also be a file path or object containing the spec.
        spec: "https://httpbin.org/spec.json"
      }
    }
  }
})
```
## Implementation

For implementation, I would suggest using [openapi-typescript](https://github.com/drwpow/openapi-typescript/tree/main/packages/openapi-typescript) as an optional peer dependency to generate the types. Some types can probably be borrowed from the `openapi-fetch` package to create the `useXXX()` types.

Note though that the latest version only supports openapi, and not swagger, which httpbin uses. Developers would have to install v5 instead of v6.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by johannschopplich** [comment]
Hey there @killjoy1221!

> A huge benefit of writing your backend endpoints using Nuxt is the type inference in `useFetch` and `$fetch`. Not only do you get types for the path, but also the request and response data. You don't get that benefit when using API Party. 

Your argument is only valid for internal Nuxt API routes, when a Nitro route handler is defined. Then, Nuxt can import the TS file and infer the response type. If you were to use `useFetch` and `$fetch` for foreign origins, you have to provide the typings yourself. Just like for Nuxt Api Party.

Having said that, a types code generator just like @diizzayy implemented in his [`nuxt-graphql-client`](https://github.com/Diizzayy/nuxt-graphql-client) would be quite useful, absolutely.

> I would suggest using [openapi-typescript](https://github.com/drwpow/openapi-typescript/tree/main/packages/openapi-typescript) as an optional peer dependency to generate the types.

Sounds good. On Nuxt init, we could fetch the types and cache them in the `.nuxt` folder. Or use the already generated `api-party.d.ts` for that. Feel free to open an PR. I will review. 🙂 

> Without types, it's not much of a party.

That made me giggle.
