### ISSUE TITLE
Clear cache on error in response

### ISSUE THREAD

**Issue by AwesomeAnders** [johannschopplich/nuxt-api-party#34]
### Describe the feature

Hello great work on this project. It's a super useful module for us that eliminates a ton of code - really appreicate the work!

I was wondering if a feature to disable or remove the cache for a reponse if the response returns an error would be possible? 

My use case is: 

i have blog/[slug]. In my nuxt page i call GET blog/{id} - if my backend returns a 404 i redirect to error page. Now if the user again tries to access the same route blog/[slug] and the backend still returns 404 my fetch in the frontend will no longer return an error object because the previous response is still in the cache and I can't check if I should redirect the user to my error page. 

I could disable caching for this route but I don't necessarily want to disable caching if the user navigates between different blog/[slug] routes and the response was a 200 the first time. 

Does this makes sense? :) 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by johannschopplich** [comment]
Makes sense, absolutely. 👍 

 I'm thinking of a `invalidateCacheOnError` option, which may even default to `true`. Could be a good default setting.

**Comment by johannschopplich** [comment]
Edit: This should be a default from my point of view. I have not implemented a `invalidateCacheOnError` option.

**Comment by AwesomeAnders** [comment]
Thank you - Amazing work! 🙏
