### ISSUE TITLE
Adding URL params to API Party config

### ISSUE THREAD

**Issue by Luuk** [johannschopplich/nuxt-api-party#4]
Hi,

I would like to add url params to my API Party config as these are required for my API to authenticate. However, I cannot find a way to include the ?api_key param at the end of url.

Format I need: API_PARTY_BASE_URL + PATH + URL_PARAMS
Example: https://api.themoviedb.org/3/movie/550?api_key=xxxxxxxxxxxxx

**Comment by johannschopplich** [comment]
Feature landed in https://github.com/johannschopplich/nuxt-api-party/commit/085a4569201c6636063adbafe1c99bdc0d435435.

Example:

```ts
export default defineNuxtConfig({
  apiParty: {
    query: {
      'foo': 'bar'
    }
  }
})
```

Or:


```ts
export default defineNuxtConfig({
  apiParty: {
    endpoints: {
      someApi: {
        query: {
          'foo': 'bar'
        }
      }
    }
  }
})
```
