### ISSUE TITLE
Global headers can be overridden

### ISSUE THREAD

**Issue by tacxou** [johannschopplich/nuxt-api-party#45]
### Describe the feature

Example ?

```ts
export const useApiFetch = <P extends GETPlainPaths<paths>>(
  path: MaybeRefOrGetter<P>,
  opts?: Omit<UseOpenApiDataOptions<paths[`/${P}`], IgnoreCase<keyof paths[`/${P}`] & "get">>, "method"> | undefined,
): AsyncData<P | undefined, FetchError<any>> => {
  return useApiData(path, <any>{
    ...opts,
    onRequest(context): Promise<void> | void {
      context.options.headers = {
        ...context.options.headers,
        'x-api-key': '123', //TODO: get api key from authjs
      }
    }
  })
}
```

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by johannschopplich** [comment]
Indeed, global headers can be overridden by any composable. This is intentional and not a bug, since for a specific request you may want to adapt a certain header, which you have already declared in the `apiParty` module options. This allows users to have full control without being bound to global defaults in every call.

```ts
useApiData(path, {
  headers: {
    // Will overriden the global `foo` header if present
    foo: 'baz'
  }
})
```

**Comment by tacxou** [comment]
> 

In fact, I want to act globally. Except that I can't type the composable so that it retains OpenAPI autocompletion. I think an example of this very common authentication case would be necessary.

**Comment by johannschopplich** [comment]
I see. Please take a look into the [module configuration docs](https://nuxt-api-party.byjohann.dev/config/). You can define global headers per API endpoint:

```ts
export default defineNuxtConfig({
  apiParty: {
    endpoints: {
      myApi: {
        url: process.env.MY_API_BASE_URL!,
        // Define global headers here. They will be used with every `$myApi` or `useMyApiData` call.
        headers: {
          Authorization: `Bearer ${process.env.MY_API_TOKEN}`
        }
      },
    }
  }
})
```

**Comment by tacxou** [comment]
What if I want to take my header from a blind in this case? Doesn't your approach work?
