### ISSUE TITLE
Headers not configured properly in nuxt.config.ts

### ISSUE THREAD

**Issue by Cupkiller-vip** [johannschopplich/nuxt-api-party#47]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.8
- Builder:          -
- User Config:      modules, devtools, imports, pinia, css, apiParty, unocss, piniaPersistedstate
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @unocss/nuxt@0.55.4, @element-plus/nuxt@1.0.5, nuxt-icons@3.2.1, @vueuse/nuxt@10.2.1, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, nuxt-api-party@0.17.0       
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/admiring-kilby-x69gsn

**This repository doesn't seem to be able to view network information properly in CodeSandbox, so you may need to launch it in VS Code.**

To avoid additional errors, the Url in the playground provided by nuxt-api-party is used here

### Describe the bug

**My English is not very good, so the following is translated from translation software. I apologize if it has caused any unnecessary trouble.**

I made the following configuration in nuxt.config.ts:
```typescript
apiParty: {
    endpoints: {
      proxyAsync: {
        url: 'https://a8i4pp1q.beesnat.com',
        headers: {
          Authorization: 'test',
        },
      },
    },
  },
``` 
I want the request to carry a request header for authentication, but it doesn't work, all web requests to the server have headers with a value of {}.

### Additional context

In my search, I found #10 issue that talks about this. I'm assuming that the issue may have something to do with the "Authorization" field.

**Comment by johannschopplich** [comment]
@Cupkiller-vip I can't reproduce your issue. 

Given the following configuration:

```ts
export default defineNuxtConfig({
  modules: ['nuxt-api-party'],

  apiParty: {
    endpoints: {
      proxyAsync: {
        url: '/api',
        headers: {
          Authorization: 'test',
        },
      },
    },
  },
})
```

And the Nuxt API route in `server/api/views.get.ts`:

```ts
export default defineEventHandler((event) => {
  const headers = getHeaders(event)
  console.log(headers)
  return {
    foo: 'bar',
  }
})
```

Will result in the following log:
```ts
{ authorization: 'test', host: 'localhost' }
```

… when called with one of the generated composables:

```ts
const { data } = await useProxyAsyncData('views')
```

I'm not sure what causes your issue, but the global headers are forwarded correctly.

**Comment by Cupkiller-vip** [comment]
> @Cupkiller-vip I can't reproduce your issue.我不能重现你的问题。
> 
> Given the following configuration:给定以下配置:
> 
> ```ts
> export default defineNuxtConfig({
>   modules: ['nuxt-api-party'],
> 
>   apiParty: {
>     endpoints: {
>       proxyAsync: {
>         url: '/api',
>         headers: {
>           Authorization: 'test',
>         },
>       },
>     },
>   },
> })
> ```
> 
> And the Nuxt API route in `server/api/views.get.ts`: `server/api/views.get.ts` 中的next API路由:
> 
> ```ts
> export default defineEventHandler((event) => {
>   const headers = getHeaders(event)
>   console.log(headers)
>   return {
>     foo: 'bar',
>   }
> })
> ```
> 
> Will result in the following log:将产生以下日志:
> 
> ```ts
> { authorization: 'test', host: 'localhost' }
> ```
> 
> … when called with one of the generated composables:当使用生成的可组合对象之一调用时:
> 
> ```ts
> const { data } = await useProxyAsyncData('views')
> ```
> 
> I'm not sure what causes your issue, but the global headers are forwarded correctly.我不确定是什么原因导致你的问题，但全局标题被正确转发。

Once I launch this project in VS Code and open it in the browser. Clicking on the button to initiate a network request, the following network information can be observed in the console.

![image](https://github.com/johannschopplich/nuxt-api-party/assets/61798525/fe9e19a5-5df4-4868-a280-c3d4d96ce1c2)

I think the headers here should carry the appropriate content. In fact, when I don't use the global headers configuration, but configure them individually for each request, it carries them correctly. I haven't tried to fetch the data on the server side, so maybe the content is being carried over, but the console isn't displaying it properly?

I apologize for this behavior of replying again in a closed issue.

**Comment by johannschopplich** [comment]
@Cupkiller-vip No, the global headers are added dynamically in the server route, just like the base URL, to protect your credentials from being leaked in the client:

https://github.com/johannschopplich/nuxt-api-party/blob/1b3999bc1909043f09be95dcfa1c2ed81367efac/src/runtime/server/handler.ts#L66

The idea behind this module is to keep global headers secret. Please read the [How It Works guide](https://nuxt-api-party.byjohann.dev/guide/how-it-works.html) to get an understanding of the inner workings of this module.
