### ISSUE TITLE
UI Freezing when uploading data through Nuxt API Party

### ISSUE THREAD

**Issue by 9M6** [johannschopplich/nuxt-api-party#48]
### Environment

 Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      nitro, vite, build, devtools, debug, ssr, css, imports, runtimeConfig, modules, apiParty
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.8.0, @nuxtjs/i18n@8.0.0-rc.4, @vueuse/nuxt@10.4.1, nuxt-typed-router@3.3.1, nuxt-lodash@2.5.0, nuxt-api-party@0.17.1, nuxt-icon@0.5.0, nuxt-pdfeasy@1.4.0
- Build Modules:    -

### Reproduction

Not applicable.

### Describe the bug

```
 const {
        data: { value: task },
        pending,
        error,
        refresh,
      } = await useConfide("vi/api/dataset/upload", {
        method: "POST",
        body: formData,
      });
```

When I'm using the above function which is a wrapper and abstraction on top of the NuxtApiParty, the UI glitches and takes a bit of time to upload, in some cases crashes the browser.

https://github.com/johannschopplich/nuxt-api-party/assets/61775571/c0974eb7-71ed-42c6-ad0a-91ea4a02ea54

On the other hand, I have done another implementation with Axios and a proxy URL with `routeRules`, and that works completely fine, no glitches, nothing.

https://github.com/johannschopplich/nuxt-api-party/assets/61775571/c81d55c0-42d9-40e6-bd17-f7e067b9d56d

**Comment by johannschopplich** [comment]
Quick notice: Please do not use the reactive upload handler `useConfide`, but `$confide` for simple upload handling instead. [See the docs](https://nuxt-api-party.byjohann.dev/api/my-api.html).

**Comment by johannschopplich** [comment]
Can you please provide a minimal reproduction?

**Comment by 9M6** [comment]
Hey @johannschopplich the problem is that the function in there is a simple wrapper of the Generated functions from API Party:

```
const cookie = useCookie("auth_c4dm");
  return useDMData<T>(
    url,
    Object.assign(
      {
        headers: {
          Authorization: `Token ${cookie.value}`,
        },
      },
      config,
    ),
  );
```

**Comment by 9M6** [comment]
As for the reproduction, I'm not sure what to provide? Like its not a bug, but more like how the library behaves. I moved that logic with Axios and everything works smooth as butter.

**Comment by johannschopplich** [comment]
Nuxt API Party will always generate two composables. In your case, `useConfide` and `$confide`. Please use the latter one for data sending. It won't cache results and is inteded for simple upload cases you currently use Axios for. As state earlier, please [read the docs](https://nuxt-api-party.byjohann.dev/api/my-api.html).

Please use a template below to create a minimal reproduction
👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
👉 https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox

**Comment by johannschopplich** [comment]
Without a reproduction, I won't be able to investigate the issue. Please open a separate issue once you found the time to create a reproducible example. Thanks in advance!
