### ISSUE TITLE
TypeScript error when using `transform` option

### ISSUE THREAD

**Issue by brawaru** [johannschopplich/nuxt-api-party#49]
### Environment

https://stackblitz.com/~/github.com/brawaru/nuxt-api-party-test (vanilla Stackblitz doesn't have Volar)

### Reproduction

0. Have API typed using OpenAPI
1. Use `useEndpointData` composable, but pass `transform` method in it to modify the response (e.g. select a subset of response data)

### Describe the bug

TypeScript will not accept your `transform` method because its return type doesn't match the original response type, neither the `data` will have a correct type. This doesn't match the reality though, as evident by result on the page after it's compiled unchecked by Vite.

### Additional context

N/A

### Logs

```shell-script
N/A
```

**Comment by johannschopplich** [comment]
Hi there!

The `transform` option is not intended to modify the result data. Let's take a look into the [`useAsyncData` types](https://nuxt.com/docs/api/composables/use-async-data#params), which is used by Nuxt API Party under the hood:

```ts
type AsyncDataOptions<DataT> = {
  server?: boolean
  lazy?: boolean
  immediate?: boolean
  default?: () => DataT | Ref<DataT> | null
  transform?: (input: DataT) => DataT
  pick?: string[]
  watch?: WatchSource[]
}
```

As the type states, the input data `DataT` has to be on par with the output data type. If you think this is a bug, please open an issue at the [Nuxt repo](https://github.com/nuxt/nuxt/issues).

If you intend to use only the `hits` of your API data, I recommend using a composable:

```ts
const { data } = await useModrinthData()
const hits = computed(() => data.value?.hits)
```

**Comment by brawaru** [comment]
> The `transform` option is not intended to modify the result data

I mean, the name implies it is. So does say the [Nuxt documentation](https://nuxt.com/docs/api/composables/use-async-data#params):

> - `transform`: a function that can be used to alter `handler` function result after resolving

And it works with vanilla Nuxt `useFetch` and `useAsyncData`, which you can check here:

https://stackblitz.com/~/github.com/brawaru/nuxt-api-testing

If it wasn't there to modify the result, then what would be the point to include it, and name it that way 😅

**Comment by brawaru** [comment]
Also that type on the site is either incorrect or harmfully oversimplified, the actual type makes use of two generics: one for the initial handler result, the other one for the transformed data.

https://github.com/nuxt/nuxt/blob/a07b34a6edb2ab900c7397fcf0965b1a468d910a/packages/nuxt/src/app/composables/asyncData.ts#L34

**Comment by johannschopplich** [comment]
@brawaru At the moment, we're just using the first generic of `AsyncDataOptions`. We probably have to add the other ones as well, just like `useFetch` does. PR welcome!

**Comment by johannschopplich** [comment]
@zAlweNy26 Please open a separate issue with a reproducible example. The playground `transform` works fine.
