### ISSUE TITLE
The refresh() is not working properly

### ISSUE THREAD

**Issue by Cupkiller-vip** [johannschopplich/nuxt-api-party#50]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.7.0
- CLI Version:      3.8.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.8
- Builder:          -
- User Config:      modules, devtools, imports, pinia, css, apiParty, unocss
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @unocss/nuxt@0.55.4, @element-plus/nuxt@1.0.5, nuxt-icons@3.2.1, @vueuse/nuxt@10.2.1, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, nuxt-api-party@0.17.0
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/sandbox/happy-rubin-r396mz

### Describe the bug

When I use refresh(), the data doesn't get updated, and even the network request doesn't happen. So I used Nuxt3's native **useFetch()**, which can send network requests even though it doesn't fetch the data properly (because no proxy is configured). 

Is this nuxt-api-party's fault? Or does it need to be written differently to achieve this effect? 

I'm sorry if this problem bothers you.

**Comment by johannschopplich** [comment]
The `useMyApiData` composable caches the responses just like earlier versions of `useFetch` did by hashing the input parameters.

Please read the [Caching Guide](https://nuxt-api-party.byjohann.dev/guide/caching.html#cache-options)to get an understanding when `useMyApiData` caches data and how to use the `cache: false` option.

**Comment by killjoy1221** [comment]
In case you want more control over caching, I made a composable for one of my endpoints that makes refresh invalidate the cache. It replicates some internal logic to calculate the key, so it might break in the future in api-party or ohash updates.

```ts
import { hash } from "ohash";

export const useCurrentUser = () => {
  const nuxt = useNuxtApp();
  const data = useAuthData("api/v1/user/@me");

  // make refresh ignore the cache

  // internal key, could break with a library update
  const userKey = `$party${hash([
    "auth", // endpointId
    "api/v1/user/@me", // path
    undefined, // query
    undefined, // method
    undefined, // body (except formdata)
  ])}`;

  const { refresh } = data;

  const refreshInvalidate: typeof refresh = async (opts) => {
    // invalidate the cache
    delete nuxt.payload.data[userKey];
    await refresh(opts);
  };

  data.refresh = refreshInvalidate;
  // awaiting gets the original asyncdata object, which is separate from the Promise
  data.then((asyncData) => {
    asyncData.refresh = refreshInvalidate;
  });

  return data;
};
```

**Comment by johannschopplich** [comment]
@killjoy1221 Thanks for your example! It also brought an idea to mind. See https://github.com/johannschopplich/nuxt-api-party/pull/51. What do you say?
