### ISSUE TITLE
Error in POST reques with body

### ISSUE THREAD

**Issue by AwesomeAnders** [johannschopplich/nuxt-api-party#54]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.5.1
- Nuxt Version:     3.7.0
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

I have some routeRules defined in my nuxt.config.ts which aprrently breaks the caching in the API party module. 
If you try to render the page **without** routeRules then it works. 
If you try to render the page **with** routeRules then it breaks. 

https://stackblitz.com/edit/github-eequg2?file=app.vue

### Describe the bug

server side POST request with body returns undefined and on client it returns an error

**Comment by johannschopplich** [comment]
Can you please provide a minimal reproducible example?

**Comment by AwesomeAnders** [comment]
I'm getting this error in my POST request after updating but I can't for the life of me figure our why it happens. 
![image](https://github.com/johannschopplich/nuxt-api-party/assets/37805682/1e3b8219-bd94-4e3a-b305-3e79adf74a15)

I tried creating a stackblitz with a repro but it works fine there.

**Comment by AwesomeAnders** [comment]
Actually! I found the issue. I have some routeRules defined in nuxt.config: 

routeRules: {
    '/api/:locale/landingpage/:tag': { swr: 900 },
    '/api/:locale/tagged-landingpage/:tag': { swr: 900 },
    '/api/:locale/navigation': { swr: 900 },
    '/api/:locale/:funnel': { swr: 900 },
    '/api/:locale/:funnel/:product': { swr: 900 },
    '/api/:locale/:funnel/:product/:area': { swr: 900 },
    '/api/:locale/:funnel/:product/:area/:site': { swr: 900 },
  },
  
  If I remove those routeRules then my POST request works again.

**Comment by AwesomeAnders** [comment]
I have created a reproduction here: 

I have some routeRules defined in my nuxt.config.ts which aprrently breaks the caching in the API party module. 

If you try to render the page **without** routeRules then it works. 
If you try to render the page **with** routeRules then it breaks. 

https://stackblitz.com/edit/github-eequg2?file=app.vue

**Comment by johannschopplich** [comment]
The behavior you encounter should happen in every other custom route which uses `readBody` and is overwritten with custom route rules. Could you please create a reproduction with a custom API route handler and post the issue upstream?
I believe every module using `addServerHandler` and being overwritten by route rules will face the same issue.

For now, I recommend to not overwrite the module's internal `/api/__api_party/:endpointId` route, but make your rules more specific instead.

If Nuxt provides a way for modules to detect custom route rules, feel free to open another issue. Thanks in advance!
