### ISSUE TITLE
useApiData: custom key is always `true`

### ISSUE THREAD

**Issue by killjoy1221** [johannschopplich/nuxt-api-party#55]
### Environment

N/a

### Reproduction

```ts
const nuxt = useNuxtApp()
console.log(Object.keys(nuxt.payload.data)) // []
await useApiData("...", {
  key: "somekey"
});
console.log(Object.keys(nuxt.payload.data)) // ["$apiPartytrue"]
```

### Describe the bug

Provide a custom key to `useApiData` and compare `nuxt.payload.data` before and after. No matter what key you use, the key will be `true`.

This line probably got missed when changing the cache key from `cache` -> `key`.
https://github.com/johannschopplich/nuxt-api-party/blob/4cc65d326edb81255689cde4d95063252efcb08d/src/runtime/composables/useApiData.ts#L125

It was also missed in `$api`
https://github.com/johannschopplich/nuxt-api-party/blob/4cc65d326edb81255689cde4d95063252efcb08d/src/runtime/composables/%24api.ts#L86

**Comment by johannschopplich** [comment]
Good catch!
