### ISSUE TITLE
Multiple Set-Cookie gets merged into one

### ISSUE THREAD

**Issue by xxRockOnxx** [johannschopplich/nuxt-api-party#58]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  bun@1.0.6
- Builder:          -
- User Config:      devtools, modules, runtimeConfig, svgo, apiParty
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @sidebase/nuxt-auth@0.6.0-rc.0, nuxt-svgo@3.5.6, nuxt-api-party@0.21.0
- Build Modules:    -
------------------------------

### Reproduction

Not sure exactly how to provide a server reproduction but the problematic code is right here: https://github.com/johannschopplich/nuxt-api-party/blob/v0.21.0/src/runtime/server/handler.ts#L75

The reproduction on this line would be the following

```
const headers = new Headers()
headers.append('Set-Cookie', 'a=a')
headers.append('Set-Cookie', 'b=b')
headers.append('Content-Type', 'application/json')

headers.getSetCookie()
['a=a', 'b=b']

Object.fromEntries(headers.entries())
{content-type: 'application/json', set-cookie: 'b=b'}
```

### Describe the bug

Multiple response headers under the same name such as "Set-Cookie" gets merged into one and thus client never receiving fully the whole cookie from server.

### Additional context

Similar case from unjs/h3 repo: https://github.com/unjs/h3/issues/384

**Comment by Saplyn** [comment]
encountered same problem. when setting multiple cookies, only the last cookie is "proxied".
