### ISSUE TITLE
Support `FormData` proxy to API endpoint

### ISSUE THREAD

**Issue by sunxyw** [johannschopplich/nuxt-api-party#6]
I'm writing a simple page for uploading files,
when using normal `$fetch` everything works fine,
but after switching to api-party, it doesn't work and I get an error: `Unknown object type "formdata"`.

Minimal Reproduction:
```vue
<template>
  <main>
    <input ref="schematicFile" accept=".schematic,.schem,.litematic" type="file" @change="onSchematicFileChanged($event)"/>
  </main>
</template>

<script setup lang="ts">
const schematicFile = ref<File | null>()
const uploading = ref(false)
const progress = ref(0.0)

interface uploadResponse {
  download_key: String,
  delete_key: String,
}

const onSchematicFileChanged = ($event: Event) => {
  const target = $event.target as HTMLInputElement
  if (target && target.files) {
    schematicFile.value = target.files[0]
    uploadSchematic()
  }
}

const uploadSchematic = async () => {
  if (!schematicFile.value) {
    return
  }

  uploading.value = true

  const formData = new FormData()
  formData.append('schematic', schematicFile.value as Blob)

  // const resp = await $uploadApi<uploadResponse>('upload', {
  const resp = await $fetch<uploadResponse>('https://ark.sunxyw.xyz/upload', {
    method: 'POST',
    body: formData,
  })
  console.log(resp)
}
</script>
```

**Comment by johannschopplich** [comment]
Yeah, there's no form data support at the very moment. It's on the roadmap.

**Comment by johannschopplich** [comment]
@sunxyw Could you please try again with v0.6.1? I've implemented `FormData` support in https://github.com/johannschopplich/nuxt-api-party/commit/63f2ab8b7327110940420e7f1c32da69b315852d.

**Comment by sunxyw** [comment]
Thanks for your work. But it doesn't seem to work.
I tried replacing `$fetch('https://ark.sunxyw.xyz/upload', { method: 'POST', body: formData })` with `$arkitektonika('upload', { method: 'POST ', body: formData })`, but it just throws a 500 error.

The FormData comes from:
```javascript
const formData = new FormData()
formData.append('schematic', schematicFile.value as Blob)
```

The request sent:
POST /api/__api_party/arkitektonika HTTP/1.1
```json
{
  "path":"upload",
  "headers":{
    "Content-Type":"multipart/form-data",
    "Content-Length":"1478"
  },
  "method":"POST",
  "body":"[object FormData]"
}
```
Response:
```json
{
  "url":"/api/__api_party/arkitektonika",
  "statusCode":500,
  "statusMessage":"Failed to fetch from API endpoint \"arkitektonika\"",
  "message":"Failed to fetch from API endpoint \"arkitektonika\"",
  "stack":"<pre><span class=\"stack internal\">at createError (./node_modules/.pnpm/h3@1.0.1/node_modules/h3/dist/index.mjs:48:15)</span>\n<span class=\"stack\">at ./.nuxt/dev/index.mjs:526:11</span>\n<span class=\"stack internal\">at async Object.handler (./node_modules/.pnpm/h3@1.0.1/node_modules/h3/dist/index.mjs:681:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.0.1/node_modules/h3/dist/index.mjs:745:7)</span></pre>",
  "data":"fetch failed ()"
}
```

I think the problem is that it converts FormData to String.

**Comment by johannschopplich** [comment]
Thank you for testing! Dang, I missed that `toString()` won't actually return the string value passed to the server when putting a `FormData` body into the `fetch` API. I tried to circumvent `FormData` serialization, but intended to create the request body the API proxy will send to the server right in the client.

There's probably no way around serializing the `FormData` object in the client, sending it to the API proxy handler and creating a new `FormData` there for the actual fetch request to the API server. 

Serialization is implemented in https://github.com/johannschopplich/nuxt-api-party/commit/8786806fa3c939482d2ba0fa5f85f2f499074d79, but I haven't tested with your setup yet. Would you mind re-testing?

**Comment by sunxyw** [comment]
I upgraded to v0.6.3, but I think it broke the normal operation.
When I try to run the development server, an error occurs.
```
 ERROR  [worker reload] [worker init] Cannot find module '<project path>/.nuxt/dev/utils.mjs' imported from <project path>/.nuxt/dev/index.mjs

  at new NodeError (node:internal/errors:393:5)
  at finalizeResolution (node:internal/modules/esm/resolve:305:11)
  at moduleResolve (node:internal/modules/esm/resolve:866:10)
  at defaultResolve (node:internal/modules/esm/resolve:1074:11)
  at nextResolve (node:internal/modules/esm/loader:164:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:839:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:426:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)
```

Inside `index.mjs`, I figured out the possible cause of the error:
```javascript
import { deserializeMaybeEncodedBody } from './utils.mjs';
```
The `utils.mjs` is missing from the `dev` directory.
I think there might be some kind of bug causing the import statement to show up here.

**Comment by johannschopplich** [comment]
Good point. Fixed in https://github.com/johannschopplich/nuxt-api-party/commit/5c7b50205cca89f3f4d5f3dd7747b601dd130292. Since we now have dependencies in the Nitro server, we will have to inline the utils into the worker bundle.

Could you please try again? 🥇

**Comment by sunxyw** [comment]
I think it works really well! I can upload my file and get a response correctly. Thank you so much for your work!

**Comment by johannschopplich** [comment]
Glad to hear! Thanks for the thorough testing.
