### ISSUE TITLE
Pass-through client request headers / set X-Forwarded for

### ISSUE THREAD

**Issue by TO-koswald** [johannschopplich/nuxt-api-party#66]
### Describe the feature

There should be an option similiar to how it's done for the response headers in #44 to pass client request headers to the server.

Use case:
- User-Agent / Client IP (X-FORWARED-FOR header)

Right now our main api receives User-Agent: node and the ip-address of the node server.

Right now to achieve this, we need to create a custom route and proxy them ourselves. We cannot set `client: true` ,because this would expose an `Authorization` header that we set.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by voidoath** [comment]
This would be an important improvement.

**Comment by zAlweNy26** [comment]
Any update on this?
