### ISSUE TITLE
Get status code from `useApiData`

### ISSUE THREAD

**Issue by m-anwr** [johannschopplich/nuxt-api-party#69]
### Describe the feature

Currently when I do this:
```
const { status } = await usApiData("/posts", { ... })
console.log(status.value)
```
I get `"success"` as long as no error happened, but I don't get any other values

It would be nice if we could get the status code by doing (for example): `status.value.code` 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by killjoy1221** [comment]
`AsyncData.status` is not the HTTP status code of the request, but the activity status of the request. It is one of `idle`, `pending`, `success`, or `error`. You can get the HTTP status code (albeit not reactively) using the `onResponse()` callback.

```ts
useApiData("endpoint", {
  onResponse(ctx) {
    const status = ctx.response.status
    console.log(`The status was: ${status}`)
  }
}
```

**Comment by johannschopplich** [comment]
@killjoy1221 Thanks a lot! I have added a dedicated page to the documentation. It will be live with the next major release.
