### ISSUE TITLE
typescript error on openapi paths with no parameters

### ISSUE THREAD

**Issue by killjoy1221** [johannschopplich/nuxt-api-party#76]
### Environment

$ npx nuxi info
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/johannschopplich/nuxt-api-party/blob/ab30c8da43d5fb1736d0fb06ecd30b50568f2b10/playground/pages/petStore.vue#L69-L82

### Describe the bug

On OpenAPI paths without parameters, the typical fetch options are not available in `useApiData` or `$api`. The options type seems to be resolving to `Record<string, never>`.

Full error:
```
Argument of type '{ method: "POST"; body: { id: number; name: string; status: "available"; photoUrls: string[]; category: { id: number; name: string; }; tags: { id: number; name: string; }[]; }; }' is not assignable to parameter of type 'OpenAPIClientFetchOptions<"POST", "post", FilterMethods<{ put: { requestBody: { content: { "application/json": { id?: number | undefined; name: string; category?: { id?: number | undefined; name?: string | undefined; } | undefined; photoUrls: string[]; tags?: { ...; }[] | undefined; status?: "pending" | ... 2 more ....'.
  Type '{ method: "POST"; body: { id: number; name: string; status: "available"; photoUrls: string[]; category: { id: number; name: string; }; tags: { id: number; name: string; }[]; }; }' is not assignable to type 'Record<string, never>'.
    Property 'method' is incompatible with index signature.
      Type 'string' is not assignable to type 'never'.
```

**Comment by johannschopplich** [comment]
That is a great catch! Thanks.
