### ISSUE TITLE
Dynamic Backend URL  bug

### ISSUE THREAD

**Issue by ye1999** [johannschopplich/nuxt-api-party#79]
### Environment

    "nuxt-api-party": "^2.0.8",

### Reproduction

const { data } = await useJsonPlaceholderData(
  'comments',
  {
    headers: {
      'Json-Placeholder-Endpoint-Url': 'https://jsonplaceholder-v2.typicode.com'
    }
  }
)

### Describe the bug

’Json-Placeholder-Endpoint-Url‘   ×
‘jsonPlaceholder-endpoint-url’ √

### Additional context

docs：https://nuxt-api-party.byjohann.dev/guide/dynamic-backend-url.html
source code：handler.ts:50  
const baseURL = new Headers(headers).get(`${endpointId}-endpoint-url`) || endpoint.url

**Comment by johannschopplich** [comment]
Thanks for the report!
