### ISSUE TITLE
How to deal with refresh token strategy?

### ISSUE THREAD

**Issue by ManUtopiK** [johannschopplich/nuxt-api-party#81]
### Describe the feature

Thanks for your nuxt-module!

I wonder if it possible to query an api that use refresh token strategy and OAuth2.
Let's say I need to query first the `/oauth2/token` endpoint to get the access and refresh token, and only after getting the token, querying another endpoint while holding the access token fresh.

How to deal with this strategy ?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [X] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by johannschopplich** [comment]
Hi there!

Of course, this module basically provides secure alternatives to Nuxt's `$fetch` and `useFetch` composables. So you can query any API and provide refresh tokens. Here's an example:

```ts
const authStore = useAuthStore()
const { isLoggedIn } = storeToRefs(authStore)

if (isLoggedIn.value && authStore.isTokenExpired()) {
  await authStore.refresh()
}

const { data } = await useMyApiData(path, {
  headers: computed(() => ({
    ...(isLoggedIn.value && {
      Authorization: `Bearer ${authStore.accessToken}`,
    }),
  })),
})
```
