### ISSUE TITLE
POST request with caching enabled and a body containing different data is treated as same request

### ISSUE THREAD

**Issue by itm-ape** [johannschopplich/nuxt-api-party#9]
Would it be possible to cache requests based on the content of the body of the request and not only the path? 

E.g. right now with caching enabled

If I make this request

```
const data = await $party(
  'some-url',
  {
    method: 'POST',
    body: {
      foo: 'bar'
    },
)
```
and afterwards the same request but with a different body 

```
const data = await $party(
  'some-url',
  {
    method: 'POST',
    body: {
      bar: 'foo'
    },
)
```

the request won't return the correct data as it will hit the cache.

**Comment by johannschopplich** [comment]
Good idea.
