### ISSUE TITLE
Caching bug on first request with dynamic query parameters

### ISSUE THREAD

**Issue by sneakylenny** [johannschopplich/nuxt-api-party#91]
### Environment

Nuxt project info:                                                                                                                                                                          12:06:59 PM

------------------------------
- Operating System: Linux
- Node Version:     v20.12.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      default
- Runtime Modules:  nuxt-api-party@2.0.11
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/devbox/jovial-lalande-3nh836?file=%2Fapp%2Fapp.vue

```vue
<script setup lang="ts">
const page = ref(2)
const { data, refresh, clear } = await useYourApiOfChoiceData('/posts', {
  query: computed(() => ({
    'page[number]': page.value
  })),
})
</script>

<template>
  <div>
    <button @click="page--">prev</button> 
    {{ page }}
    <button @click="page++">next</button>
    <button @click="clear()">Clear</button>
    <button @click="refresh()">Refresh</button>
    <pre v-text="data" />
  </div>
</template>
```

### Describe the bug

The data is retrieved successfully on first request and the data is cached. When the query changes, the second request is made. This request is also cached. When requesting the same data from the first request, you'd expect the cached result to be returned. However, the data is still equal to the second request.

My suspicion is that the first request is cached incorrectly or not accessible when changing the query params. Possibly `undefined` cache key or due to it being processed server side?

I've tried manually setting a cache key with the page number in combination with `import.meta.server` but this yields the same results.

Related:
https://github.com/johannschopplich/nuxt-api-party/issues/14

### Additional context

After discovering this bug I wanted to disable the cache altogether, however this option does not exist in the ApiEndpoint or ModuleOptions interfaces. [source](https://nuxt-api-party.byjohann.dev/config/#type-declaration)

I may create 2 separate PR's referencing this issue, but that would happen in my spare time.

**Comment by sneakylenny** [comment]
I noticed there is no use of the getCachedData option found in the [useAsyncData params](https://nuxt.com/docs/api/composables/use-async-data#params). Is there a reason for this? It could simplify the caching process.

**Comment by sneakylenny** [comment]
I'll give it a try, I think I can make it work with `getCachedData` if there are no objections.

**Comment by sneakylenny** [comment]
### Hitting a wall

Apparently I can't use `getCachedData` as in it's current state as it's not able to replace the way this package implemented caching already. I tried to implement it, but the `getCachedData` is never called again. Even when the watched data changes. Nuxt has an issue about it over here: https://github.com/nuxt/nuxt/issues/24332. They labeled it as a "nice-to-have" so I don't think we could make use of it anytime soon. Which makes the default way of caching the best way right now.

### As for my discoveries trying to fix the bug:

When I remove `_key.value` on [line 183 in useApiData.ts](https://github.com/johannschopplich/nuxt-api-party/blob/da9a2bb8d0c70ae38105dabb774e7f39ac428a80/src/runtime/composables/useApiData.ts#L183):

```diff
  return useAsyncData<T, unknown>(
-    _key.value,
    async (nuxt) => {
```

This results in the cache not "hanging" like described in the issue. Not quite sure why this is or if it's essential to have the key there?

#### Any objections to removing the line?

The behavior it exhibits is:
- It fetches the data on refresh
- When updating the querydata (or the watched data) it fetches new data
- When returning to the initial request it show the correct cached data and does not hang on the data of the last fetch
- When setting `cache: false` if omits all of this and correctly disables the cache.

**Comment by johannschopplich** [comment]
Thanks for the tests!

The problem is: Without the `key` in the `useAsyncData` composable, Nuxt will generate a key at build-time. This means that all async data requests would use the same key. Thus, we have to provide this key.

However, you can customize it. Have you followed the [custom cache key guide](https://nuxt-api-party.byjohann.dev/api/use-fetch-like.html#caching)?

**Comment by sneakylenny** [comment]
That's unfortunate. 
I tried to use the custom key but it yields the same result. I don't know how else I could solve this issue right now.

I've been working on adding a `cache` option for each endpoint defined. I got a working implementation. However, I'm not satisfied with the way it's implemented. I will close this as I consider this stalled for the moment.

**Comment by sneakylenny** [comment]
I went for the manual proxy route. I got a lot of projects I require a proxy for so I developed multiple methods to accomplish a solid proxies that work for development and production. 

### Method 1 (quick):

In some projects I use [`h3-proxy`](https://github.com/yisibell/h3-proxy) which also has a Nuxt plugin: [`nuxt-proxy-request`](https://github.com/yisibell/nuxt-proxy-request).

### Method 2 (flexible - no extra dependencies):

In my personal projects I usually go for a manual proxy using only h3 helper functions because I require more flexibility regarding what happens in-between:

<details>
  <summary>Click to show `server/api/(proxies)/myapi/[...].ts` snippet</summary>

```ts
export default defineEventHandler(async (event) => {
 const url = useRuntimeConfig(event).backendUrl + event.path!.replace(/^\/api\/myapi/, '')
 const requestBody = hasBody ? await readRawBody(event) : undefined

  const response = await fetchWithEvent(event, url, {
    method,
    headers: getHeaders(event) as HeadersInit,
    body: requestBody,
  })

  // Proxy cookies from backend to frontend
  appendResponseHeader(event, 'set-cookie', response.headers.getSetCookie())

  const responseBody = await response.json()

  return responseBody
})
```
</details>

"(proxies)" explaned: https://nuxt.com/docs/guide/directory-structure/pages#route-groups
"[...].ts" explained: https://nuxt.com/docs/guide/directory-structure/server#catch-all-route

### But what about the cache?

For both methods I use a "custom useFetch" which the Nuxt docs suggests you add if you require default options for fetching your api: https://nuxt.com/docs/guide/recipes/custom-usefetch. 

If I require data to be cached I use either the [default caching provided by useFetch](https://nuxt.com/docs/getting-started/data-fetching#caching-and-refetching) or [`@pinia/colada-nuxt`](https://pinia-colada.esm.dev/nuxt.html)

**Comment by jonty-comp** [comment]
@sneakylenny Thanks for your detailed reply!

I looked into doing it manually initially, but thought `nuxt-api-party` was excellent particularly because of its OpenAPI support - There are undoubtedly ways of getting the same functionality if I roll my own proxy, but it all seems to work very well here!

I'll keep looking at ways to sort this problem out for now - at least if I do need to change approach down the line, it should be mostly a find-and-replace job to use a different calling function.
