### ISSUE TITLE
Cached or not-cached?

### ISSUE THREAD

**Issue by Asparagirl** [johannschopplich/nuxt-api-party#94]
### Describe the feature

Hi there. When using the one-time ```$myApi``` style composable with the ```cache: true```, is there some way we could get an optional response that we could log, to show that the response was cached or not?

The reason I ask is that I'm currently using it to grab very large JSON responses from an external API, and would like to have some way to measure how many times I'm getting a one-off unique data fetch vs. how many times I've gotten cached data because a certain call was made already or was made often.

Also, how long do responses stay in the cache, and is it limited by number of responses, or by overall size of the response(s), or by time, or...? And could we get that added to the docs, please?

Thanks. :-)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-api-party/issues).

**Comment by johannschopplich** [comment]
Hi there!

In general, if the item is cached, it is cached indefinetly during the run of your application. Unless you manually clear the cache with `clear()` or you use computed query parameters, headers, etc. that have changed and trigger a refresh. If the computed key based on all of the input parameters change, the cache will be cleared.

Please follow the [caching guide](https://nuxt-api-party.byjohann.dev/guide/caching.html) to learn more about how the cache keys is built.

If you want to inspect if the request was cached, I recommend you use the [Nuxt DevTools](https://devtools.nuxt.com/). All state items starting with `apiParty` are managed by Nuxt API Party:

![Screenshot 2024-12-25 at 11-03-07 Nuxt API Party](https://github.com/user-attachments/assets/84d75741-6074-4f55-a48b-9f3478ef4317)
